{% set name = "act-atmos" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 124506888bffca27f197bccd5460d86ed75e39274bf46e9c450c7963ba2f3985

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyproj >=2.3.1
    - pandas
    - xarray
    - matplotlib
    - numpy
    - scipy
    - astral
    - dask
    - distributed
    - pint
    - cartopy
    - metpy
    - boto3
    - netcdf4

test:
  requires:
    - pytest
  imports:
    - act
  commands:
    - py.test --pyargs act

about:
  home: https://github.com/ANL-DIGR/ACT
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Python library for working with atmospheric time-series by n-dimension datasets'

  description: |
    Toolkit for working with atmospheric data in every aspect
    of the scientific process.  From discovery and downloading,
    to visualization, to retrievals and advanced calculations
  doc_url: https://anl-digr.github.io/ACT/
  dev_url: https://anl-digr.github.io/ACT/

extra:
  recipe-maintainers:
    - AdamTheisen
    - rcjackson
    - zssherman
