{% set name = "act-atmos" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2f2f7781d88dec642c4d7e55923fc6a59d6904b5223cd4511d06cffaee8414c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyproj >=2.3.1
    - pandas
    - xarray
    - matplotlib-base <=3.2.2
    - numpy
    - scipy
    - dask
    - distributed
    - pint
    - cartopy <=0.17.0
    - metpy
    - boto3
    - netcdf4
    - six
    - requests
    - arm_pyart
    - astral

test:
  requires:
    - pytest
  imports:
    - act
  commands:
    - py.test --pyargs act

about:
  home: https://github.com/ARM-DOE/ACT
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python library for working with atmospheric time-series by n-dimension datasets

  description: |
    Toolkit for working with atmospheric data in every aspect
    of the scientific process.  From discovery and downloading,
    to visualization, to retrievals and advanced calculations
  doc_url: https://arm-doe.github.io/ACT/
  dev_url: https://github.com/ARM-DOE/ACT

extra:
  recipe-maintainers:
    - AdamTheisen
    - rcjackson
    - zssherman
    - jhemedin
