travis:
  secure:
    BINSTAR_TOKEN: j0Xl5BRo2IYV1JiGqccaSV5z/09aA4pDbgQrn3Z051Xi9jBphvGFs9GZKmAehdP8VFJWYCkFT16upF5nlSWKRCEo/mzkn122Jp8kedv+UAcs4VqHLlWSYn8wx75xaFiz4pmkCUBap/Mha2wxUKYUyvWrFDJ92GM60mQco/QX/5myTFOWtg5Y1+uN84qXi/yE6jgizfwl6qEcxVMoqmYRslqBFbiWx1tF7kSySXxogxGai2GSXUksM86PsY03eUGMCa5ZR3FQ++Q7O9NYmRe7ZpnH1kYYsxkdbA98/ybaa7e6p0S8xCmMJPmgTfHfJs6FlQJRVDMdIq2YhVrAhEgCdsF40/6gb4fHww0qevhScs4680r5d1m/AnSUbTX9/fUdoqU8ui2I6jjUoVfI0I8WpYjDUrkLlUSSXDnFTSNYxdBMCybZ9D09N9sLsNyUEM2Vd9vbMf7sfSo+FHEHjDfy/a0gbd/BnBNR5qZuY1LLsHOM+39m0I/9H4BaDQylf+8P7vE/xmLtXq+4bFwzASRNep95c18Agf8GWycJS/2QnydE+puUH3RYjvOFpDDkSjJlZ2kk3tR2lQsMN13MqfyJAMxnm41UU3lSLQ9SlYV7FgZcEfBBJz5eK7kFzpCafLzBeoCkC95aXgV7yyHmxAAcusxhI6pSWQswwJvLQCVkdMo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
